#	SELECT * FROM CART;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE CART;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CART(				
	CRT_NO INT AUTO_INCREMENT PRIMARY KEY,
	CRT_M_NO INT,
	CRT_P_NO INT,
	CRT_AMOUNT INT,
	FOREIGN KEY (CRT_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (CRT_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

/* INSERT */
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 18, 2);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 15, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 4, 3);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 12, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 10, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 7, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 1, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(4, 24, 2);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 38, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 11, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 36, 2);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 16, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 13, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(5, 22, 1);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(6, 8, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(6, 2, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(6, 32, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(6, 17, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(6, 21, 1);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(7, 29, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(7, 13, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(7, 8, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(7, 38, 1);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(8, 25, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(8, 18, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(8, 38, 1);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(9, 14, 1);
INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(9, 23, 1);

INSERT INTO CART(CRT_M_NO, CRT_P_NO, CRT_AMOUNT) VALUES(10, 39, 1);
