-- DROP TABLE CART CASCADE CONSTRAINTS;

-- SELECT * FROM CART;

DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE CART;
CREATE TABLE CART(					-- 장바구니테이블
	CRT_NO NUMBER PRIMARY KEY,		-- 장바구니번호
	CRT_M_NO NUMBER,				-- 회원번호
	CRT_P_NO NUMBER,				-- 제품번호
	CRT_AMOUNT NUMBER,				-- 제품수량
	FOREIGN KEY (CRT_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (CRT_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

-- INSERT --
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,18,2);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,15,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,4,3);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,12,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,10,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,7,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,1,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,4,24,2);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,38,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,11,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,36,2);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,16,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,13,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,5,22,1);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,6,8,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,6,2,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,6,32,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,6,17,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,6,21,1);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,7,29,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,7,13,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,7,8,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,7,38,1);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,8,25,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,8,18,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,8,38,1);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,9,14,1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,9,23,1);

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL,10,39,1);

