SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE Q_REPLY;
DROP TABLE R_REPLY;
DROP TABLE REPLY;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP TABLE REVIEWS;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE MEMBERS;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE MEMBERS(
	M_NO INT AUTO_INCREMENT PRIMARY KEY,
    M_ID VARCHAR(50) NOT NULL UNIQUE,
    M_PW VARCHAR(64) NOT NULL,
    M_NAME VARCHAR(50) NOT NULL,
  	M_ADDR1 VARCHAR(20),
  	M_ADDR2 VARCHAR(100),
  	M_ADDR3 VARCHAR(100),
    M_PHONE VARCHAR(20) NOT NULL,
    M_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    M_COUPON INT DEFAULT 0,
    M_POINT INT DEFAULT 2000,
    M_GRADE VARCHAR(20) DEFAULT '일반등급',
    M_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT(					
	IDX DOUBLE NOT NULL,
    P_NO INT AUTO_INCREMENT PRIMARY KEY,
    P_NAME VARCHAR(200) NOT NULL,
    P_SIZE VARCHAR(50) NOT NULL,
    P_PRICE INT NOT NULL,
    P_COLOR VARCHAR(30),
    P_AMOUNT INT NOT NULL,
    P_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	P_CATEGORY VARCHAR(50) NOT NULL,
	P_IMAGE VARCHAR(200),
	P_FABRIC VARCHAR(200),
	P_INFORMATION VARCHAR(1000)
);

CREATE TABLE CART(				
	CRT_NO INT AUTO_INCREMENT PRIMARY KEY,
	CRT_M_NO INT,
	CRT_P_NO INT,
	CRT_AMOUNT INT,
	FOREIGN KEY (CRT_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (CRT_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE ORDERS(
	O_NO INT AUTO_INCREMENT PRIMARY KEY,
	O_M_NO INT NOT NULL,
	O_P_NO INT NOT NULL,
	O_AMOUNT VARCHAR(10) NOT NULL,
	O_REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	O_NAME VARCHAR(30),
	O_ADDR1 VARCHAR(20) NOT NULL,
	O_ADDR2 VARCHAR(100) NOT NULL,
	O_ADDR3 VARCHAR(100),
	O_CELLPHONE VARCHAR(100) NOT NULL,
	O_PAYMENT VARCHAR(10) NOT NULL,
	O_NOTE VARCHAR(4000),
	O_PRICE VARCHAR(100) NOT NULL,
	O_POINT VARCHAR(20),
	O_IDX INT,
	O_DELIVERY VARCHAR(100) DEFAULT '배송준비중',
	FOREIGN KEY (O_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (O_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE REVIEWS(
	RV_NO INT AUTO_INCREMENT PRIMARY KEY,
	RV_TITLE VARCHAR(100) NOT NULL,
	RV_CONTENT VARCHAR(500) NOT NULL,
	RV_REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RV_HIT INT NOT NULL,
	RV_FILENAME VARCHAR(300),
	RV_M_NO INT NOT NULL,
	RV_P_NO INT NOT NULL,
	FOREIGN KEY (RV_M_NO) REFERENCES MEMBERS (M_NO),
	FOREIGN KEY (RV_P_NO) REFERENCES PRODUCT (P_NO)
);

CREATE TABLE QNA(
	Q_NO INT AUTO_INCREMENT PRIMARY KEY,
	Q_M_NO INT,
	Q_P_NO INT,
	Q_TITLE VARCHAR(200) NOT NULL,
	Q_CONTENT VARCHAR(1000) NOT NULL,
	Q_PW VARCHAR(30),
	Q_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Q_HIT INT,
	Q_FILENAME VARCHAR(300),
	Q_SECRET VARCHAR(20),
	FOREIGN KEY (Q_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (Q_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE NOTICE(
	N_NO INT AUTO_INCREMENT PRIMARY KEY,
	N_TITLE VARCHAR(100) NOT NULL,
	N_M_NO INT,
	N_CONTENT LONGTEXT,
	N_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	N_HIT INT,
	N_FILENAME VARCHAR(4000),
	FOREIGN KEY (N_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

CREATE TABLE REPLY(
	R_NO INT AUTO_INCREMENT PRIMARY KEY,
	R_WRITER VARCHAR(100) NOT NULL,
	R_REWRITER VARCHAR(100),
	R_CONTENT VARCHAR(4000),
	R_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	R_EDITDATE TIMESTAMP,
	R_N_NO INT,
	R_M_NO INT,
	R_DELETE INT,
	R_GROUP INT,
	R_GROUPORD INT,
	R_DEPTH INT,
	FOREIGN KEY (R_N_NO) REFERENCES NOTICE (N_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

CREATE TABLE R_REPLY(
	R_NO INT AUTO_INCREMENT PRIMARY KEY,
	R_WRITER VARCHAR(100) NOT NULL,
	R_REWRITER VARCHAR(100),
	R_CONTENT VARCHAR(4000),
	R_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	R_EDITDATE TIMESTAMP,
	R_RV_NO INT,
	R_M_NO INT,
	R_DELETE INT,
	R_GROUP INT,
	R_GROUPORD INT,
	R_DEPTH INT,
	FOREIGN KEY (R_RV_NO) REFERENCES REVIEWS (RV_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

CREATE TABLE Q_REPLY(
	R_NO INT AUTO_INCREMENT PRIMARY KEY,
	R_WRITER VARCHAR(100) NOT NULL,
	R_REWRITER VARCHAR(100),
	R_CONTENT VARCHAR(4000),
	R_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	R_EDITDATE TIMESTAMP,
	R_DELETE INT,
	R_GROUP INT,
	R_GROUPORD INT,
	R_DEPTH INT,
	R_Q_NO INT REFERENCES QNA (Q_NO) ON DELETE CASCADE,
	R_M_NO INT REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);