DROP TABLE Q_REPLY CASCADE CONSTRAINTS;
DROP TABLE R_REPLY CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;

DROP SEQUENCE Q_REPLY_SEQ;
DROP SEQUENCE R_REPLY_SEQ;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE QNA_SEQ;
DROP SEQUENCE REVIEWS_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE MEMBERS_SEQ;

CREATE SEQUENCE MEMBERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE REVIEWS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE QNA_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE R_REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
CREATE SEQUENCE Q_REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE TABLE MEMBERS(							-- 회원테이블
    M_NO NUMBER PRIMARY KEY,					-- 회원번호
    M_ID VARCHAR2(50) NOT NULL UNIQUE,			-- 회원ID
    M_PW VARCHAR2(64) NOT NULL,					-- 회원PW
    M_NAME VARCHAR2(50) NOT NULL,				-- 회원이름
  	M_ADDR1 VARCHAR2(20),            		 	-- 회원주소
  	M_ADDR2 VARCHAR2(100),          		  	-- 회원주소
  	M_ADDR3 VARCHAR2(100),               		-- 회원주소
    M_PHONE VARCHAR2(20) NOT NULL,				-- 회원핸드폰번호
    M_EMAIL VARCHAR2(100) NOT NULL UNIQUE,		-- 회원이메일
    M_COUPON NUMBER DEFAULT 0,					-- 회원쿠폰
    M_POINT NUMBER DEFAULT 2000,				-- 회원적립금
    M_GRADE VARCHAR2(20) DEFAULT '일반등급',	-- 회원등급
    M_REGDATE DATE	DEFAULT SYSDATE 			-- 회원가입일
);

CREATE TABLE PRODUCT(						-- 제품테이블
	IDX NUMBER NOT NULL,					-- 제품인덱스 (같은제품 사이즈 같으면 같은 번호입니다.)
    P_NO NUMBER PRIMARY KEY,				-- 제품번호
    P_NAME VARCHAR2(200) NOT NULL,			-- 제품명
    P_SIZE VARCHAR2(50) NOT NULL,			-- 제품size(ex: S, M ,L)
    P_PRICE NUMBER NOT NULL,				-- 제품가격
    P_COLOR VARCHAR2(30),					-- 제품색상
    P_AMOUNT NUMBER NOT NULL,				-- 제품수량
    P_REGDATE DATE,							-- 제품등록일
	P_CATEGORY VARCHAR2(50) NOT NULL,		-- 제품카테고리
	P_IMAGE VARCHAR2(200),					-- 제품사진
	P_FABRIC VARCHAR2(200),					-- 제품섬유정보
	P_INFORMATION VARCHAR2(1000)			-- 제품정보
);

CREATE TABLE CART(					-- 장바구니테이블
	CRT_NO NUMBER PRIMARY KEY,		-- 장바구니번호
	CRT_M_NO NUMBER,				-- 회원번호
	CRT_P_NO NUMBER,				-- 제품번호
	CRT_AMOUNT NUMBER,				-- 제품수량
	FOREIGN KEY (CRT_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (CRT_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE ORDERS(							-- 주문테이블
	O_NO NUMBER PRIMARY KEY,					-- 주문번호
	O_M_NO NUMBER NOT NULL,						-- 회원번호
	O_P_NO NUMBER NOT NULL,						-- 상품번호
	O_AMOUNT VARCHAR2(10) NOT NULL,				-- 주문수량
	O_REGDATE DATE NOT NULL,					-- 주문일자
	O_NAME VARCHAR2(30),						-- 주문자이름
	O_ADDR1 VARCHAR2(20) NOT NULL,				-- 수령자주소
	O_ADDR2 VARCHAR2(100) NOT NULL,				-- 수령자주소
	O_ADDR3 VARCHAR2(100),						-- 수령자주소
	O_CELLPHONE VARCHAR2(100) NOT NULL,			-- 수령자연락처
	O_PAYMENT VARCHAR2(10) NOT NULL,			-- 결제방법
	O_NOTE VARCHAR2(4000),						-- 기타메모
	O_PRICE VARCHAR2(100) NOT NULL,				-- 주문금액
	O_POINT VARCHAR2(20),
	O_IDX NUMBER,
	O_DELIVERY VARCHAR2(100) DEFAULT '배송준비중',
	FOREIGN KEY (O_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (O_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE REVIEWS(
	RV_NO NUMBER PRIMARY KEY,							-- 리뷰번호
	RV_TITLE VARCHAR2(100) NOT NULL,					-- 리뷰제목
	RV_CONTENT VARCHAR2(500) NOT NULL,					-- 리뷰내용
	RV_REGDATE DATE NOT NULL,							-- 리뷰등록일
	RV_HIT NUMBER NOT NULL,								-- 조회수
	RV_FILENAME VARCHAR2(300),							-- 첨부파일
	RV_M_NO NUMBER NOT NULL,							-- 작성자의 회원번호
	RV_P_NO NUMBER NOT NULL,							-- 제품번호
	FOREIGN KEY (RV_M_NO) REFERENCES MEMBERS (M_NO),	-- 작성자 회원번호
	FOREIGN KEY (RV_P_NO) REFERENCES PRODUCT (P_NO)	-- 제품번호
);

CREATE TABLE QNA(								-- QNA 테이블
	Q_NO NUMBER PRIMARY KEY,					-- 문의번호
	Q_M_NO NUMBER,								-- 작성자 NO
	Q_P_NO NUMBER,								-- 제품번호
	Q_TITLE VARCHAR2(200) NOT NULL,				-- 문의제목
	Q_CONTENT VARCHAR2(1000) NOT NULL,			-- 문의내용
	Q_PW VARCHAR2(30),							-- 비밀번호
	Q_DATE DATE,								-- 작성일
	Q_HIT NUMBER,								-- 조회수
	Q_FILENAME VARCHAR2(300),					-- 첨부파일
	Q_SECRET VARCHAR(20),						-- 비밀글 유무 (y,n)
	FOREIGN KEY (Q_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (Q_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

CREATE TABLE NOTICE(
	N_NO NUMBER PRIMARY KEY,							-- 공지 번호
	N_TITLE VARCHAR2(100) NOT NULL,						-- 공지 제목
	N_M_NO NUMBER,										-- 회원 번호
	N_CONTENT CLOB,										-- 공지 내용
	N_DATE DATE,										-- 공지 작성일
	N_HIT NUMBER,										-- 공지 조회수
	N_FILENAME VARCHAR2(4000),							-- 공지 첨부파일
	FOREIGN KEY (N_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE	
);

CREATE TABLE REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_N_NO NUMBER,
	R_M_NO NUMBER,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	FOREIGN KEY (R_N_NO) REFERENCES NOTICE (N_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

CREATE TABLE R_REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_RV_NO NUMBER,
	R_M_NO NUMBER,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	FOREIGN KEY (R_RV_NO) REFERENCES REVIEWS (RV_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

CREATE TABLE Q_REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	R_Q_NO NUMBER REFERENCES QNA (Q_NO) ON DELETE CASCADE,
	R_M_NO NUMBER REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);