#	SELECT * FROM PRODUCT;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE PRODUCT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PRODUCT(					
	IDX DOUBLE NOT NULL,
    P_NO INT AUTO_INCREMENT PRIMARY KEY,
    P_NAME VARCHAR(200) NOT NULL,
    P_SIZE VARCHAR(50) NOT NULL,
    P_PRICE INT NOT NULL,
    P_COLOR VARCHAR(30),
    P_AMOUNT INT NOT NULL,
    P_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	P_CATEGORY VARCHAR(50) NOT NULL,
	P_IMAGE VARCHAR(200),
	P_FABRIC VARCHAR(200),
	P_INFORMATION VARCHAR(1000)
);

/* INSERT */
INSERT INTO PRODUCT(IDX, P_NO, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(0, 0, ' ', ' ', 0, NULL, 0, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), ' ', NULL, NULL, NULL);
UPDATE PRODUCT SET P_NO = 0 WHERE P_NO = 1;
ALTER TABLE PRODUCT AUTO_INCREMENT = 1;

/* OUTER */
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(1, 'HALF DOUBLE LONG COAT', 'S', 288000, 'CHARCOAL', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_01_HALF%20DOUBLE%20LONG%20COAT%20%5BCHARCOAL%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(1, 'HALF DOUBLE LONG COAT', 'M', 288000, 'CHARCOAL', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_01_HALF%20DOUBLE%20LONG%20COAT%20%5BCHARCOAL%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(1, 'HALF DOUBLE LONG COAT', 'L', 288000, 'CHARCOAL', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_01_HALF%20DOUBLE%20LONG%20COAT%20%5BCHARCOAL%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(2, 'HALF DOUBLE LONG COAT', 'S', 288000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_02_HALF%20DOUBLE%20LONG%20COAT%20%5BNAVY%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(2, 'HALF DOUBLE LONG COAT', 'M', 288000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_02_HALF%20DOUBLE%20LONG%20COAT%20%5BNAVY%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(2, 'HALF DOUBLE LONG COAT', 'L', 288000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_02_HALF%20DOUBLE%20LONG%20COAT%20%5BNAVY%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(3, 'OUT POCKET PEA COAT', 'S', 268000, 'HERRINGBONE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_03_OUT%20POCKET%20PEA%20COAT%20%5BHERRINGBONE%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(3, 'OUT POCKET PEA COAT', 'M', 268000, 'HERRINGBONE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_03_OUT%20POCKET%20PEA%20COAT%20%5BHERRINGBONE%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(3, 'OUT POCKET PEA COAT', 'L', 268000, 'HERRINGBONE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_03_OUT%20POCKET%20PEA%20COAT%20%5BHERRINGBONE%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(4, 'OUT POCKET PEA COAT', 'S', 268000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_04_OUT%20POCKET%20PEA%20COAT%20%5BNAVY%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(4, 'OUT POCKET PEA COAT', 'M', 268000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_04_OUT%20POCKET%20PEA%20COAT%20%5BNAVY%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(5, 'WOOL MAXI-OVER MAC COAT', 'S', 288000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_05_WOOL%20MAXI-OVER%20MAC%20COAT%20%5BCHARCOAL%20CHECK%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(5, 'WOOL MAXI-OVER MAC COAT', 'M', 288000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_05_WOOL%20MAXI-OVER%20MAC%20COAT%20%5BCHARCOAL%20CHECK%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(5, 'WOOL MAXI-OVER MAC COAT', 'L', 288000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_05_WOOL%20MAXI-OVER%20MAC%20COAT%20%5BCHARCOAL%20CHECK%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(6, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'S', 258000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_06_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BCHARCOAL%20CHECK%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(6, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'M', 258000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_06_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BCHARCOAL%20CHECK%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(6, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'L', 258000, 'CHARCOAL CHECK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_06_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BCHARCOAL%20CHECK%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(7, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'S', 258000, 'AQUA MARINE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_07_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BAQUA%20MARINE%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', '일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다.
롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(7, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'M', 258000, 'AQUA MARINE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_07_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BAQUA%20MARINE%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(7, 'SEMI-OVER MARSEILE DOUBLE JACKET', 'L', 258000, 'AQUA MARINE', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_07_SEMI-OVER%20MARSEILE%20DOUBLE%20JACKET%20%5BAQUA%20MARINE%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(8, 'Military Over Coat', 'S', 368000, 'Herringbone', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_08_Military%20Over%20Coat%20%5BHerringbone%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(8, 'Military Over Coat', 'M', 368000, 'Herringbone', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_08_Military%20Over%20Coat%20%5BHerringbone%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(8, 'Military Over Coat', 'L', 368000, 'Herringbone', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_08_Military%20Over%20Coat%20%5BHerringbone%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(9, '909 Single Jacket', 'S', 148000, 'Black', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_09_909%20Single%20Jacket%20%5BBlack%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(9, '909 Single Jacket', 'M', 148000, 'Black', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_09_909%20Single%20Jacket%20%5BBlack%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(9, '909 Single Jacket', 'L', 148000, 'Black', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'OUTER', 'resources/storage/p_09_909%20Single%20Jacket%20%5BBlack%5D.jpg', '', '');

/* BOTTOM */
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(10, '20SS_Technical Semi-Wide slacks[wool blend]', 'S', 119000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_10_20SS_Technical%20Semi-Wide%20slacks%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(10, '20SS_Technical Semi-Wide slacks[wool blend]', 'M', 119000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_10_20SS_Technical%20Semi-Wide%20slacks%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(10, '20SS_Technical Semi-Wide slacks[wool blend]', 'L', 119000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_10_20SS_Technical%20Semi-Wide%20slacks%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(11, 'NOAH Merino Wool One Tuck Pants', 'S', 129000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_11_NOAH%20Merino%20Wool%20One%20Tuck%20Pants%20%5BBLACK%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(11, 'NOAH Merino Wool One Tuck Pants', 'M', 129000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_11_NOAH%20Merino%20Wool%20One%20Tuck%20Pants%20%5BBLACK%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(11, 'NOAH Merino Wool One Tuck Pants', 'L', 129000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BOTTOM', 'resources/storage/p_11_NOAH%20Merino%20Wool%20One%20Tuck%20Pants%20%5BBLACK%5D.jpg', '', '');

/* BAG */
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(12, 'Saddle Mini-Bag [Eppi leather]', 'FREE', 148000, 'NAVY', 0, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BAG', 'resources/storage/p_12_Saddle%20Mini-Bag%20%5BEppi%20leather%5D%20%5BNAVY%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');

/* BLACKFRIDAY */
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(13, '20SS_Modern Half-Double Blazer [wool blend]', 'S', 199000, 'NAVY', 0, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_13_20SS_Modern%20Half-Double%20Blazer%20%5Bwool%20blend%5D%20%5BNAVY%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(13, '20SS_Modern Half-Double Blazer [wool blend]', 'M', 199000, 'DARK NAVY', 0, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_13_20SS_Modern%20Half-Double%20Blazer%20%5Bwool%20blend%5D%20%5BNAVY%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(13, '20SS_Modern Half-Double Blazer [wool blend]', 'L', 199000, 'NAVY', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_13_20SS_Modern%20Half-Double%20Blazer%20%5Bwool%20blend%5D%20%5BNAVY%5D.jpg', '', '');

INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(14, '20SS_New Collarless Blazer [wool blend]', 'S', 199000, 'BLACK', 0, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_14_20SS_New%20Collarless%20Blazer%20%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', 
'겉감 : WOOL 90% POLYAMIDE 10% 안감 : VISCOSE 43% POLY 57% 부자재 : REAL HORN', 
'일자 오버핏으로 포멀하게 떨어지는 트렌디한 패턴을 적용하여 캐주얼하면서도 격식있게 연출 가능합니다. 롱한 기장감이지만 적당한 중량감과 두께감으로 한 겨울에도 착용가능합니다.');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(14, '20SS_New Collarless Blazer [wool blend]', 'M', 199000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_14_20SS_New%20Collarless%20Blazer%20%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', '', '');
INSERT INTO PRODUCT(IDX, P_NAME, P_SIZE, P_PRICE , P_COLOR, P_AMOUNT, P_REGDATE, P_CATEGORY, P_IMAGE, P_FABRIC, P_INFORMATION) VALUES(14, '20SS_New Collarless Blazer [wool blend]', 'L', 199000, 'BLACK', 10, STR_TO_DATE('12/02/2020', '%m/%d/%Y'), 'BLACKFRIDAY', 'resources/storage/p_14_20SS_New%20Collarless%20Blazer%20%5Bwool%20blend%5D%20%5BBLACK%5D.jpg', '', '');
