#	SELECT * FROM Q_REPLY;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE Q_REPLY;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Q_REPLY(
	R_NO INT AUTO_INCREMENT PRIMARY KEY,
	R_WRITER VARCHAR(100) NOT NULL,
	R_REWRITER VARCHAR(100),
	R_CONTENT VARCHAR(4000),
	R_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	R_EDITDATE TIMESTAMP,
	R_DELETE INT,
	R_GROUP INT,
	R_GROUPORD INT,
	R_DEPTH INT,
	R_Q_NO INT REFERENCES QNA (Q_NO) ON DELETE CASCADE,
	R_M_NO INT REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

/* INSERT */
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('관리자1', NULL, '고객님 주문넣어주신상품 확인결과 저희는 당일배송을 원칙으로 하고있으나 공장에서 물건이 늦어질경우 최소 3일~4일정도 기간이 소요됩니다.', STR_TO_DATE('12/07/2020', '%m/%d/%Y'), NOW(), 0, 0, 0, 0, 1, 1);
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('관리자1', NULL, '원래 재질이 그렇습니다^^', STR_TO_DATE('12/11/2020', '%m/%d/%Y'), NOW(), 0, 2, 0, 0, 2, 1);
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('홍길동', NULL, '환불해주세요', STR_TO_DATE('12/11/2020', '%m/%d/%Y'), NOW(), 0, 2, 1, 1, 2, 4);
INSERT INTO Q_REPLY(R_WRITER, R_REWRITER, R_CONTENT, R_DATE, R_EDITDATE, R_DELETE, R_GROUP, R_GROUPORD, R_DEPTH, R_Q_NO, R_M_NO) VALUES('관리자2', NULL, '손상된 제품 환불이 어렵습니다~', STR_TO_DATE('12/12/2020', '%m/%d/%Y'), NOW(), 0, 2, 2, 2, 2, 2);
