-- DROP TABLE Q_REPLY CASCADE CONSTRAINTS;

-- SELECT * FROM Q_REPLY;

DROP SEQUENCE Q_REPLY_SEQ;
CREATE SEQUENCE Q_REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE Q_REPLY;
CREATE TABLE Q_REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	R_Q_NO NUMBER REFERENCES QNA (Q_NO) ON DELETE CASCADE,
	R_M_NO NUMBER REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

-- INSERT --
INSERT INTO Q_REPLY VALUES(Q_REPLY_SEQ.NEXTVAL,'관리자1',NULL,'원래 재질이 그렇습니다^^',SYSDATE,SYSDATE,0,1,0,0,1,1);
INSERT INTO Q_REPLY VALUES(Q_REPLY_SEQ.NEXTVAL,'홍길동',NULL,'환불해주세요',SYSDATE,SYSDATE,0,1,1,1,1,4);
INSERT INTO Q_REPLY VALUES(Q_REPLY_SEQ.NEXTVAL,'관리자2',NULL,'손상된 제품 환불이 어렵습니다~',SYSDATE,SYSDATE,0,1,2,2,1,2);