#	SELECT * FROM QNA;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE QNA;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE QNA(
	Q_NO INT AUTO_INCREMENT PRIMARY KEY,
	Q_M_NO INT,
	Q_P_NO INT,
	Q_TITLE VARCHAR(200) NOT NULL,
	Q_CONTENT VARCHAR(1000) NOT NULL,
	Q_PW VARCHAR(30),
	Q_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Q_HIT INT,
	Q_FILENAME VARCHAR(300),
	Q_SECRET VARCHAR(20),
	FOREIGN KEY (Q_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE,
	FOREIGN KEY (Q_P_NO) REFERENCES PRODUCT (P_NO) ON DELETE CASCADE
);

/* INSERT */
INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(5, 12, '배송문의', '언제도착하나요', NULL, STR_TO_DATE('12/06/2020', '%m/%d/%Y'), 0, NULL, 'n');

INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(4, 20, '먼가요', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/11/2020', '%m/%d/%Y'), 0, 'review1.jpg', 'y');
INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(4, 13, '이상해요', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/11/2020', '%m/%d/%Y'), 0, 'review2.jpg', 'y');

INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(5, 23, '문의드립니다', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/13/2020', '%m/%d/%Y'), 0, 'review3.jpg', 'y');
INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(5, 17, '진짜머죠', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/13/2020', '%m/%d/%Y'), 0, 'review4.jpg', 'y');

INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(6, 31, '진짜로우', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/16/2020', '%m/%d/%Y'), 0, 'review5.jpg', 'y');
INSERT INTO QNA(Q_M_NO, Q_P_NO, Q_TITLE, Q_CONTENT, Q_PW, Q_DATE, Q_HIT, Q_FILENAME, Q_SECRET) VALUES(6, 9, '정말로', '단추가다떨어졌어요', '1q2w3e4r', STR_TO_DATE('12/16/2020', '%m/%d/%Y'), 0, 'review6.jpg', 'y');
