-- DROP TABLE R_REPLY CASCADE CONSTRAINTS;

-- SELECT * FROM R_REPLY;

DROP SEQUENCE R_REPLY_SEQ;
CREATE SEQUENCE R_REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE R_REPLY;
CREATE TABLE R_REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_RV_NO NUMBER,
	R_M_NO NUMBER,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	FOREIGN KEY (R_RV_NO) REFERENCES REVIEWS (RV_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

-- INSERT --
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'홍길동',NULL,'오.. 엄청나네요',SYSDATE,SYSDATE,1,4,0,1,0,0);
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'고종수',NULL,'우와.. 엄청나네요',SYSDATE,SYSDATE,1,14,0,1,1,1);
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'박세리',NULL,'굉장해 엄청나',SYSDATE,SYSDATE,1,15,0,3,0,0);
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'김현아',NULL,'모델같아요',SYSDATE,SYSDATE,1,16,0,3,1,1);
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'김수지',NULL,'모델맞는데요?',SYSDATE,SYSDATE,1,17,0,3,3,2);
INSERT INTO R_REPLY VALUES(R_REPLY_SEQ.NEXTVAL,'박수진',NULL,'색감이 너무 좋아요~',SYSDATE,SYSDATE,1,18,0,3,2,2);