-- DROP TABLE REPLY CASCADE CONSTRAINTS;

-- SELECT * FROM REPLY;

DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE REPLY;
CREATE TABLE REPLY(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_REWRITER VARCHAR2(100),
	R_CONTENT VARCHAR2(4000),
	R_DATE DATE,
	R_EDITDATE DATE,
	R_N_NO NUMBER,
	R_M_NO NUMBER,
	R_DELETE NUMBER,						-- 삭제여부(삭제: -1, 정상: 0)
	R_GROUP NUMBER,							-- 게시글이 같은 그룹인가?(어떤 게시글과 거기에 달린 댓글들은 모두 같은 그룹)
	R_GROUPORD NUMBER,						-- 게시글 순서(같은 그룹 내에서 표시되는 순서)
	R_DEPTH NUMBER,							-- 게시글인가? 댓글인가? (게시글: 0, 댓글: 1 이상)
	FOREIGN KEY (R_N_NO) REFERENCES NOTICE (N_NO) ON DELETE CASCADE,
	FOREIGN KEY (R_M_NO) REFERENCES MEMBERS (M_NO) ON DELETE CASCADE
);

-- INSERT --