-- DROP TABLE REVIEWS CASCADE CONSTRAINTS;

-- SELECT * FROM REVIEWS;

DROP SEQUENCE REVIEWS_SEQ;
CREATE SEQUENCE REVIEWS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE REVIEWS;
CREATE TABLE REVIEWS(
	RV_NO NUMBER PRIMARY KEY,							-- 리뷰번호
	RV_TITLE VARCHAR2(100) NOT NULL,					-- 리뷰제목
	RV_CONTENT VARCHAR2(500) NOT NULL,					-- 리뷰내용
	RV_REGDATE DATE NOT NULL,							-- 리뷰등록일
	RV_HIT NUMBER NOT NULL,								-- 조회수
	RV_FILENAME VARCHAR2(300),							-- 첨부파일
	RV_M_NO NUMBER NOT NULL,							-- 작성자의 회원번호
	RV_P_NO NUMBER NOT NULL,							-- 제품번호
	FOREIGN KEY (RV_M_NO) REFERENCES MEMBERS (M_NO),	-- 작성자 회원번호
	FOREIGN KEY (RV_P_NO) REFERENCES PRODUCT (P_NO)	-- 제품번호
);


-- INSERT --
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'정말좋네요','옷입어봤는데너무좋아요',SYSDATE,0,'review1.jpg',4,20);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'이뻐요요','잘입고있어요',SYSDATE,0,'review2.jpg',4,13);

INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'생각보다별로에요','후회합니다',SYSDATE,0,'review2.jpg',5,12);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'정말좋네요','옷입어봤는데너무좋아요',SYSDATE,0,'review3.jpg',5,23);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'괜찮아요','매우괜찮아요',SYSDATE,0,'review4.jpg',5,17);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'상당합니다','상당히 좋아요우',SYSDATE,0,'review2.jpg',5,14);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'정말좋아요','네 정말입니다',SYSDATE,0,'review5.jpg',5,30);

INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'매우좋아요','매우입니다',SYSDATE,0,'review5.jpg',6,31);
INSERT INTO REVIEWS VALUES(REVIEWS_SEQ.NEXTVAL,'입어보니알겠어요','입어보세요',SYSDATE,0,'review6.jpg',6,9);